ValueError: Exception encountered when calling layer "sequential_8" "                 f"(type Sequential).
    
    Input 0 of layer "dense_24" is incompatible with the layer: expected axis -1 of input shape to have value 14, but received input with shape (None, 14, 24)
    
    Call arguments received by layer "sequential_8" "                 f"(type Sequential):
      • inputs=tf.Tensor(shape=(None, 14, 24), dtype=float32)
      • training=True
      • mask=None
